# Generated by Django 5.2.1 on 2025-05-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joueur',
        ),
        migrations.AddField(
            model_name='match',
            name='format_bo',
            field=models.CharField(choices=[('BO1', 'BO1'), ('BO3', 'BO3'), ('BO5', 'BO5')], default='BO3', max_length=4),
        ),
        migrations.AddField(
            model_name='pari',
            name='score_pari',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pari',
            name='choix',
            field=models.CharField(max_length=100),
        ),
    ]
